apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authsvc.fullname" . }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  database-migrator-url: {{ .Values.secrets.databaseMigratorUrl | quote }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  jwt-private-key-pem: {{ .Values.secrets.jwtPrivateKeyPem | quote }}
  jwt-public-key-pem: {{ .Values.secrets.jwtPublicKeyPem | quote }}
  bootstrap-secret: {{ .Values.secrets.bootstrapSecret | quote }}
  mfa-encryption-key: {{ .Values.secrets.mfaEncryptionKey | quote }}
  data-encryption-key: {{ .Values.secrets.dataEncryptionKey | quote }}
  metrics-bearer-token: {{ .Values.secrets.metricsBearerToken | quote }}
